### ISSUE TITLE
Does inactivity indicate abandonment?

### ISSUE THREAD

**Issue by photex** [simonask/w#12]
Howdy!

Before suggesting a fork of wayward into perhaps a dedicated org so that others can keep the ball rolling on some of these open PRs and perhaps continue the work you've done I'd just like to ask whether you've lost the time or interest in continuing work on wayward. If so, what happened? Something upstream? Something in the core design?
There are not a lot of C++ http service implementations built around libevent/libevhtp and I think it makes this project rather valuable.

Addressing #10 in particular would be very helpful.

**Comment by darwin67** [comment]
+1 agree

**Comment by Skeen** [comment]
+1

**Comment by pablin87** [comment]
Hi ! for my this is a very interesting project. I would really like we can make a fork of this project an continue working on it.
So +1

**Comment by GuacheSuede** [comment]
@simonask What do you think Simon ?

**Comment by Globik** [comment]
Симон хуй забил на проект.
